services:
  django:
    build: ./django
    ports:
      - "8000:8000"
    volumes:
      - ./django:/app
    environment:
      - PYTHONUNBUFFERED=1
    init: true

  spring:
    build: ./spring/voyage
    ports:
      - "8080:8080"
    environment:
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - DB_PATH=/app/database/voyagedb
    volumes:
      - ./spring_data:/app/database
    init: true

  angular:
    build: ./angular/agence-voyage
    ports:
      - "4200:80"
    init: true

  # 👉 MISE À JOUR : Service React en mode Production pur
  react:
    build: ./react/agence-de-voyage-react
    ports:
      - "5173:80" # Mappe le port 5173 de ton PC sur le port 80 de Nginx
    init: true