# Generated by Django 5.1.4 on 2026-05-09 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prix_paye", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date_confirmation", models.DateTimeField(blank=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("EN_ATTENTE", "En attente"),
                            ("CONFIRME", "Confirmé"),
                            ("ANNULE", "Annulé"),
                        ],
                        default="EN_ATTENTE",
                        max_length=20,
                    ),
                ),
                (
                    "stripe_payment_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Utilisateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=100, unique=True)),
                ("mot_de_passe", models.CharField(max_length=255)),
                ("role", models.CharField(default="ROLE_USER", max_length=20)),
                ("date_inscription", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "UTILISATEUR",
            },
        ),
        migrations.CreateModel(
            name="Voyage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ville_depart", models.CharField(max_length=100)),
                ("ville_arrivee", models.CharField(max_length=100)),
                ("prix_total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "note_moyenne",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("nombre_places_total", models.IntegerField(default=50)),
                ("statut", models.CharField(default="A_VENIR", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Billet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("siege", models.CharField(max_length=10)),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billets",
                        to="voyages.reservation",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="reservation",
            name="utilisateur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="voyages.utilisateur",
            ),
        ),
        migrations.CreateModel(
            name="Segment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordre", models.IntegerField()),
                ("ville_depart", models.CharField(max_length=100)),
                ("ville_arrivee", models.CharField(max_length=100)),
                ("heure_depart", models.DateTimeField()),
                ("heure_arrivee", models.DateTimeField()),
                (
                    "voyage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="voyages.voyage",
                    ),
                ),
            ],
            options={
                "ordering": ["ordre"],
            },
        ),
        migrations.AddField(
            model_name="reservation",
            name="voyage",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="voyages.voyage",
            ),
        ),
        migrations.CreateModel(
            name="Avis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.IntegerField()),
                ("commentaire", models.TextField(blank=True, null=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avis",
                        to="voyages.utilisateur",
                    ),
                ),
                (
                    "voyage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avis",
                        to="voyages.voyage",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Avis",
                "ordering": ["-date_creation"],
            },
        ),
    ]
